### ISSUE TITLE
Additional conf for A003

### ISSUE THREAD

**Issue by rgaudin** [openzim/_python-bootstrap#15]
[A003](https://beta.ruff.rs/docs/rules/builtin-attribute-shadowing/) prevents redefinition of builtins. I am in favor of keeping the rule but it's true that our models frequently uses an `id` variable which raises A003.

I propose we use `builtins-ignorelist` to allow `id` (only for now)

```toml
[tool.ruff.flake8-builtins]
builtins-ignorelist = ["id"]
```
