### ISSUE TITLE
Add FastAPI exceptions for B008

### ISSUE THREAD

**Issue by rgaudin** [openzim/_python-bootstrap#16]
FastAPI's `Depends()` raises [`flake8-bugbear`](https://beta.ruff.rs/docs/settings/#flake8-bugbear-extend-immutable-calls).

Some explanation at https://github.com/tiangolo/fastapi/issues/1522

I propose:

```toml
[tool.ruff.flake8-bugbear]
# Allow default arguments like, e.g., `data: List[str] = fastapi.Query(None)`.
extend-immutable-calls = ["fastapi.Depends", "fastapi.Query"]
```

The FastAPI tickets mentions imports inside `fastapi.params` as well 

```toml
[tool.ruff.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.params.Depends", "fastapi.Query", "fastapi.params.Query"]
```
